server.port=8001
spring.application.name=hampers
spring.data.mongodb.uri=mongodb+srv://euphoriahamperofficial_db_user:CR3sIkTdHtBK0Uup@cluster0.blgmwhz.mongodb.net/?appName=Cluster0
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=hampers
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
google.client.id=CLIENT_ID